dist: trusty
sudo: false
language: python
python:
- "2.6"
- "2.7"
- "3.2"
- "3.3"
- "3.4"
- "3.5"
- "3.6"
- "3.7-dev"
install:
- pip install pydiatra pyflakes
script:
- nosetests -v
- python -m pydiatra test.py
- pyflakes test.py

# vim:ts=2 sts=2 sw=2 et
