name: CI
on:
- push
- pull_request
jobs:
  main:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        include:
        - python-version: '2.3'
          os: ubuntu-18.04
          deadsnakes: deadsnakes
        - python-version: '2.4'
          os: ubuntu-18.04
          deadsnakes: deadsnakes
        - python-version: '2.5'
          os: ubuntu-18.04
          deadsnakes: deadsnakes
        - python-version: '2.6'
          os: ubuntu-18.04
          deadsnakes: deadsnakes
        - python-version: '2.7'
          os: ubuntu-20.04
        - python-version: '3.1'
          os: ubuntu-18.04
          deadsnakes: deadsnakes
        - python-version: '3.2'
          os: ubuntu-18.04
          deadsnakes: deadsnakes
        - python-version: '3.3'
          os: ubuntu-18.04
        - python-version: '3.4'
          os: ubuntu-18.04
        - python-version: '3.5'
          os: ubuntu-18.04
        - python-version: '3.6'
          os: ubuntu-20.04
        - python-version: '3.7'
          os: ubuntu-20.04
        - python-version: '3.8'
          os: ubuntu-20.04
        - python-version: '3.9'
          os: ubuntu-20.04
        - python-version: '3.10'
          os: ubuntu-20.04
        - python-version: '3.11-dev'
          os: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{matrix.python-version}}
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.python-version}}
      if: ${{!matrix.deadsnakes}}
    - name: Set up Python ${{matrix.python-version}} (via deadsnakes PPA)
      run: |
        sudo apt-add-repository -y ppa:deadsnakes/ppa
        sudo apt-get install python${{matrix.python-version}}
      if: ${{matrix.deadsnakes}}
    - name: run tests
      run: |
        v=${{matrix.python-version}}
        v=${v%-*}
        python$v -c 'import sys; print(sys.version)'
        python$v test.py -v
    - name: run pydiatra
      run: |
        pip install pydiatra
        python -m pydiatra test.py
      if: ${{!matrix.deadsnakes}}
    - name: run pyflakes
      run: |
        pyflakes=pyflakes
        if [[ ${{matrix.python-version}} = 2.6 ]]; then pyflakes+='<2'; fi
        if [[ ${{matrix.python-version}} = 3.[23] ]]; then pyflakes+='<2'; fi
        pip install $pyflakes
        pyflakes test.py
      if: ${{!matrix.deadsnakes}}
    - name: check README syntax
      run: |
        python3 -m pip install --user pygments restructuredtext-lint
        rst-lint --level=info --encoding=UTF-8 README
      if: ${{!matrix.deadsnakes}}

# vim:ts=2 sts=2 sw=2 et
